export PATH="/opt/homebrew/opt/llvm/bin:/opt/homebrew/bin:$PATH"
export PS1="µ--Ϟ--» "
alias vim="nvim"
alias vi="nvim"
alias gcc="/opt/homebrew/opt/gcc/bin/gcc-14"
alias g++="/opt/homebrew/opt/gcc/bin/g++-14"
