[font]
normal =      { family = "Hack Nerd Font Mono", style = "Regular" }
bold =        { family = "Hack Nerd Font Mono", style = "Bold" }
italic =      { family = "Hack Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Hack Nerd Font Mono", style = "Bold Italic" }

[keyboard]
bindings = [
  { key = "=", mods = "Control",         action = "IncreaseFontSize" },
  { key = "-", mods = "Control",         action = "DecreaseFontSize" },
  { key = "C", mods = "Control|Shift",   action = "Copy" },
  { key = "V", mods = "Control|Shift",   action = "Paste" },
]
